export const ALL_PREINSCRIPTIONS_REQUEST="ALL_PREINSCRIPTIONS_REQUEST"
export const ALL_PREINSCRIPTIONS_SUCCES="ALL_PREINSCRIPTIONS_SUCCES"
export const ALL_PREINSCRIPTIONS_FAIL="ALL_PREINSCRIPTIONS_FAIL"

export const PREINSCRIPTION_DETAILS_REQUEST="PREINSCRIPTION_DETAILS_REQUEST"
export const PREINSCRIPTION_DETAILS_SUCCES="PREINSCRIPTION_DETAILS_SUCCES"
export const PREINSCRIPTION_DETAILS_FAIL="PREINSCRIPTION_DETAILS_FAIL"

export const ADMIN_ORDERS_REQUEST="ADMIN_ORDERS_REQUEST"
export const ADMIN_ORDERS_SUCCESS="ADMIN_ORDERS_SUCCESS"
export const ADMIN_ORDERS_FAIL="ADMIN_ORDERS_FAIL"

export const CREATE_PREINSCRIPTION_REQUEST="CREATE_PREINSCRIPTION_REQUEST"
export const CREATE_PREINSCRIPTION_SUCCESS="CREATE_PREINSCRIPTION_SUCCESS"
export const CREATE_PREINSCRIPTION_RESET="CREATE_PREINSCRIPTION_RESET"
export const CREATE_PREINSCRIPTION_FAIL="CREATE_PREINSCRIPTION_FAIL"

export const DELETE_PREINSCRIPTION_REQUEST="DELETE_PREINSCRIPTION_REQUEST"
export const DELETE_PREINSCRIPTION_SUCCESS="DELETE_PREINSCRIPTION_SUCCESS"
export const DELETE_PREINSCRIPTION_FAIL="DELETE_PREINSCRIPTION_FAIL"

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL'





export const  CLEAR_ERRORS="CLEAR_ERRORS"