export const ALL_SERVICES_REQUEST="ALL_SERVICES_REQUEST"
export const ALL_SERVICES_SUCCES="ALL_SERVICES_SUCCES"
export const ALL_SERVICES_FAIL="ALL_SERVICES_FAIL"

export const SERVICE_DETAILS_REQUEST="SERVICE_DETAILS_REQUEST"
export const SERVICE_DETAILS_SUCCES="SERVICE_DETAILS_SUCCES"
export const SERVICE_DETAILS_FAIL="SERVICE_DETAILS_FAIL"

export const  CLEAR_ERRORS="CLEAR_ERRORS"